### ISSUE TITLE
Switching vars in call to geom_threedpie()  can cause error message

### ISSUE THREAD

**Issue by sfd99** [coolbutuseless/ggthreed#3]
**Mike -** 
One last very quick question, (if I may).

This works fine:
> ggplot(mtcars) +
     geom_threedpie(aes(as.factor(**cyl**))) +
     facet_wrap(~**gear**, labeller = label_both) +
     theme_void() + theme(legend.position="bottom")

but ,
(if I simply switch the vars **cyl** and **gear**),
then it doesn't work:
> ggplot(mtcars) +
     geom_threedpie(aes(as.factor(**gear**))) +
     facet_wrap(~**cyl**, labeller = label_both) +
     theme_void() + theme(legend.position="bottom")
_returns_:
**_Error in grid.Call.graphics(C_polygon, x$x, x$y, index) :
  invalid line type_**

How to avoid the error message? .
What am I doing wrong?. **_THANKS, Mike!!_**

**Comment by coolbutuseless** [comment]
Thanks for the report @sfd99 

I believe this is due to an empty factor level for cyl = 8, gear = 4.  

Will investigate ...

**Comment by coolbutuseless** [comment]
I've just made some changes and this now works for me (b7c8b6ab).

**Comment by sfd99** [comment]
new **threed PKG v0.1.1**
works perfectly now!.

Mike - you are an ACE.
Looking forward
to updates to this great pkg.
_Love it!_.
