### ISSUE TITLE
How to add labels on this Pie

### ISSUE THREAD

**Issue by YanglabWCH** [coolbutuseless/ggthreed#4]
Hi coolbutuseless,

ggthread is a great package, but how could I add labels on this pie or near pie? Like this:
![image](https://user-images.githubusercontent.com/9391198/50210791-01c10600-03b2-11e9-8324-58f2de20dec7.png)

Thanks a lot.

Bests,
Shisheng

**Comment by coolbutuseless** [comment]
At present you would have to manually add these values using ggplot2::annotate.

I'm not against the idea of including such a feature, but I'm not planning on trying to implement it anytime soon.

**Comment by ghost** [comment]
I would also like it a lot if this feature can be implemented!
